config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence:true, length: {minimum: 6, maximum: 100}
	validates :description, presence:true, length: {minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	has_many :articles
	validates :username, 	presence: true, 
							uniqueness: { case_sensitive: false }, 
							length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, 	presence: true, 
						uniqueness: { case_sensitive: false }, 
						length: {maximum: 105},
						format: {with: VALID_EMAIL_REGEX}
	has_secure_password				

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only:[:show, :update, :edit, :destroy]

	def show
	end

	def index
		@articles = Article.all
	end
	def new
		@article = Article.new
	end

	def update
		if @article.update(article_params)
			flash[:notice] = "Update succesfull"
			redirect_to @article
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def edit
	end

	def create
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:notice] = "Article was created succesfully."
			redirect_to @article
		else
			render :new, status: :unprocessable_entity
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	private
	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
		
	def show
		@user = User.find(params[:id])
		@articles = @user.articles
	end	

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Welcome to the Alpha blog #{@user.username}, you have succesfully signed up."
			redirect_to articles_path
		else 
			render 'new', status: :unprocessable_entity	
		end	
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "Your account was updated."
			redirect_to articles_path
		else
			render 'edit', status: :unprocessable_entity
		end	
	end	

	
	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="row clearfix ">
	<% @articles.each do |article|%>
	
		<div class="col-lg-3">
			<div class="card mt-2" style="height: 350px">
				<h5 class="card-title" style="text-indent: 10px"><%= link_to truncate(article.title, length: 15), article_path(article), class:"text-success"%></h5>
				<div class="card-header fst-italic">
					Featured
				</div>
				<div class="card-body">
					<p class="card-text"><%= truncate(article.description, length: 100) %></p>
					
					
				
				</div>
				<div class="card-footer text-body-secondary">
					<div class="row">
						<div class="col-5">
						<small><%= article.created_at.strftime("%Y-%m-%d")%></small>
						</div>
						<div class="col-7">
						<%= link_to 'Edit', edit_article_path(article), class:"btn btn-outline-warning btn-sm" %>
						<%= link_to 'Delete', article_path(article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-outline-danger btn-sm" %>
						</div>
					</div>	
				</div>
			</div>
		</div>		
	
	<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container-md">
	
	<div class="row justify-content-center">
		<div class="col-8">
			<%= render 'shared/errors', obj: @article %>
			<%= form_with(model: @article, class:"p-3 mb-3 bg-info rounded", local:true) do |f|%>
				<div class="row mb-3">
					<%= f.label :title, class:"col-2 col-form-label" %>
					<div class="col-10">
					<%= f.text_field :title, class:"form-control"%>
					</div>
				</div>
				<div class="row mb-3">
					<%= f.label :description, class:"col-2 col-form-label" %>
					<div class="col-10">
					<%= f.text_area :description, class:"form-control", rows:"8" %>
					</div>
				</div>

				<div class="row mb-3 justify-content-center">
					<%= f.submit class:"btn btn-outline-dark btn-md col-2"%>
				</div>
			<% end %>
			<%= link_to '[ Cancel and return to articles ]', articles_path, class:"text-black" %>
		</div>
		
	</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit your article</h1>



<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>
	
	<%=render 'article' %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>


<%= render 'form' %>

app/views/articles/show.html.erb
	<h1 class="text-center mt-4"><%= @article.title%></h1>
	<div class="row justify-content-center">
		<div class="col-lg-10">
			<div class="card mt-2" style="height: 350px">
				<div class="card-header fst-italic">
					Featured
				</div>
				<div class="card-body">
					<p class="card-text"><%= simple_format(@article.description) %></p>
					
					
				
				</div>
				<div class="card-footer text-body-secondary">
					<div class="row">
						<div class="col-5">
						<small>Added by: <%= @article.user.username if @article.user%></small>:
						<small><%= time_ago_in_words(@article.created_at)%> ago</small>
						</div>
						<div class="col-7 text-end">
						<%= link_to 'Edit', edit_article_path(@article), class:"btn btn-outline-warning btn-sm" %>
						<%= link_to 'Delete', article_path(@article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-outline-danger btn-sm" %>
						</div>
					</div>	
				</div>
			</div>
		</div>		
	

</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer">
	<div class="container-fluid text-center py-4 bg-dark mt-4 text-white">
		Copyright &copy; <%= link_to "Richard Kachyňa","https://github.com/Tacud1810", class:"text-white" %>
	</div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= msg %>
    </div>      
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    
    <%= link_to "ALPHA BLOG", root_path, class:"navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class:"nav-link "%>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New article', new_article_path, class:"dropdown-item" %></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation'%>
    <div id="page-content" class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>  
    <%= render 'layouts/footer'%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page too.</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="image-home-page">
	<div class="text-center" id="welcome-sentence" >
	  <h1>Welcome to my home page</h1>
	</div>
	<br>
	<div class="text-center">
		 <%= link_to 'Signup', signup_path, class:"btn btn-success btn-md" %>
	</div>
  </div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		<h4 class="alert-heading">The following errors prevented <%= obj.class.name.downcase %> from saving</h4>
		<ul>
				<% obj.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		  
	
	</div>
<% end %>

app/views/users/_form.html.erb
<div class="container-md">
	
	<div class="row justify-content-center">
		<div class="col-8">
			<%= render 'shared/errors', obj: @user %>
			<%= form_with(model: @user, class:"p-3 mb-3 bg-info rounded", local:true) do |f|%>
				<div class="row mb-3">
					<%= f.label :username, class:"col-2 col-form-label" %>
					<div class="col-10">
					<%= f.text_field :username, class:"form-control", placeholder: "Enter a username"%>
					</div>
				</div>
				<div class="row mb-3">
					<%= f.label :email, class:"col-2 col-form-label" %>
					<div class="col-10">
					<%= f.email_field :email, class:"form-control", placeholder: "Enter your email address" %>
					</div>
				</div>
				<div class="row mb-3">
					<%= f.label :password, class:"col-2 col-form-label" %>
					<div class="col-10">
					<%= f.password_field :password, class:"form-control", placeholder: "Choose a password" %>
					</div>
				</div>

				<div class="row mb-3 justify-content-center">
					<%= f.submit(@user.new_record? ? "Sign up" : "Update account", class:"btn btn-outline-dark btn-md col-3")%>
				</div>
			<% end %>
			<%= link_to '[ Cancel and return to articles ]', articles_path, class:"text-black" %>
		</div>
		
	</div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your info</h1>



<%= render 'form' %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for alpha blog</h1>


<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= render 'articles/article' %>